daygate/urls.py
from django.urls import path, include

urlpatterns = [
    path(r"", include("deploy.urls")),
    path(r"i18n/", include("django.conf.urls.i18n")),
]

deploy/urls.py
from django.urls import path, re_path, include, reverse_lazy
from django.contrib.auth.decorators import login_required
from django_otp.decorators import otp_required
from django.contrib.auth import views as auth_views
from .views import *
from .forms import CustomAuthenticationForm, CustomPasswordChangeForm, EmailChangeForm

urlpatterns = [
    path(r"", login_required(StatusView.as_view()), name="index"),
    path(
        r"accounts/login/",
        auth_views.LoginView.as_view(authentication_form=CustomAuthenticationForm),
        name="login",
    ),
    path(
        r"accounts/logout/",
        login_required(auth_views.LogoutView.as_view()),
        name="logout",
    ),
    path(r"accounts/totp/", login_required(totp), name="totp"),
    path(
        r"accounts/email_change/",
        login_required(
            EmailChangeView.as_view(
                form_class=EmailChangeForm, success_url=reverse_lazy("deploy")
            )
        ),
        name="email_change",
    ),
    path(
        r"accounts/password_change/",
        login_required(
            CustomPasswordChangeView.as_view(
                form_class=CustomPasswordChangeForm, success_url=reverse_lazy("deploy")
            )
        ),
        name="password_change",
    ),
    path(r"backup/", otp_required(BackupFormView.as_view()), name="backup"),
    path(r"deploy/", login_required(DeployFormView.as_view()), name="deploy"),
    path(
        r"domain_setup/",
        login_required(
            DomainSetUpView.as_view(
                form_class=DomainSetUpForm, success_url=reverse_lazy("deploy")
            )
        ),
        name="domain_setup",
    ),
    path(
        r"logs/download/<container_id>/",
        login_required(log_download),
        name="log_download",
    ),
    path(r"nsupdate/", login_required(DNSUpdateFormView.as_view()), name="nsupdate"),
    path(r"nuke/", otp_required(NuclearOptionFormView.as_view()), name="nuke"),
    path(
        r"power_control/",
        otp_required(PowerControlFormView.as_view()),
        name="power_control",
    ),
    path(r"status/", login_required(StatusView.as_view()), name="status"),
    path(
        r"totp/add/",
        login_required(TOTPAddDeviceFormView.as_view()),
        name="totp_add_device",
    ),
    path(r"totp/qrcode/<key>/", login_required(qrcode), name="qrcode"),
    path(
        r"totp/remove/",
        otp_required(TOTPRemoveDeviceFormView.as_view()),
        name="totp_remove_device",
    ),
    path(
        r"totp/static/",
        otp_required(StaticTokensFormView.as_view()),
        name="static_tokens",
    ),
    path(
        r"settings/",
        login_required(SettingsFormView.as_view(form_class=SettingsForm)),
        name="settings",
    ),
    path(
        r"ssh_keys/add/", otp_required(AddSSHKeyFormView.as_view()), name="add_ssh_key"
    ),
    path(
        r"ssh_keys/delete/<pk>/",
        otp_required(DeleteSSHKeyFormView.as_view()),
        name="delete_ssh_key",
    ),
    re_path(
        r"ssh_keys/(list/)?",
        otp_required(ListSSHKeysView.as_view()),
        name="list_ssh_keys",
    ),
    path(r"updates/", login_required(UpdateFormView.as_view()), name="updates"),
    path(r"vpn/client/", otp_required(VPNClientView.as_view()), name="vpn_client"),
    path(
        r"vpn/download/", otp_required(vpn_client_download), name="vpn_client_download"
    ),
]

deploy/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from sshpubkeys import SSHKey as ssh


class Config(models.Model):
    key = models.CharField("key", max_length=128, primary_key=True)
    value = models.CharField("value", max_length=128, null=True)


class Language(models.Model):
    code = models.CharField("code", max_length=2, db_index=True, primary_key=True)
    name = models.CharField("name", max_length=128)

    def __unicode__(self):
        return "{0}".format(self.name)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    force_password_change = models.BooleanField(default=True)
    force_email_change = models.BooleanField(default=True)
    pgp_key = models.TextField(max_length=4096, null=True)
    encrypt_emails = models.BooleanField(default=False)


class SSHKey(models.Model):
    fingerprint = models.CharField("Fingerprint", max_length=48, primary_key=True)
    pubkey = models.TextField("Public key", max_length=1024)
    name = models.CharField("Name", max_length=128)
    created = models.DateTimeField("Created", auto_now=True)
    added_by = models.ForeignKey(
        User, verbose_name="Added by", on_delete=models.CASCADE
    )
    enabled = models.BooleanField("Enabled", default=True)

    def save(self, *args, **kwargs):
        key = ssh(self.pubkey)
        try:
            key.parse()
        except Exception as err:
            raise ValidationError("Invalid key:", err)
        self.name = self.pubkey.split(" ")[-1]
        self.fingerprint = key.hash_md5()
        super(SSHKey, self).save(*args, **kwargs)

deploy/views.py
# -*- coding: utf-8 -*-
import json, os.path, pytz
from ast import literal_eval
from datetime import datetime
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, DeleteView, FormView
from django.views.generic import TemplateView
from django.http import (
    HttpResponse,
    HttpResponseRedirect,
    HttpResponseBadRequest,
    Http404,
)
from django.urls import reverse, reverse_lazy
from django.utils.translation import ugettext
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import views as auth_views
from django.contrib.auth import update_session_auth_hash
from django_otp import login as django_otp_login
from django_otp.decorators import otp_required
from django_otp.forms import OTPTokenForm
from django_otp.plugins.otp_totp.models import TOTPDevice
from django_otp.plugins.otp_static.models import StaticDevice, StaticToken
from django.shortcuts import render, redirect
from django.utils.translation import ugettext, LANGUAGE_SESSION_KEY
from functools import partial
from .forms import (
    SettingsForm,
    AddSSHKeyForm,
    BackupForm,
    DeployForm,
    DNSUpdateForm,
    DomainSetUpForm,
    EmailChangeForm,
    StaticTokensForm,
    TOTPAddDeviceForm,
    TOTPRemoveDeviceForm,
    CustomPasswordChangeForm,
    UpdateForm,
    PowerControlForm,
    NuclearOptionForm,
)
from .functions import (
    needs_verification,
    render_qrcode,
    get_config,
    set_config,
    get_profile,
    set_profile,
    get_user,
    set_user,
    parse_docker_status,
    parse_filesystem_status,
    get_container_status,
    json2log,
)
from .models import Config, SSHKey
from .diceware import Diceware


def totp(request):
    """
    prompt users to verify with TOTP if they have a device set up
    """
    if needs_verification(request):
        # present them with a challenge
        form_class = partial(OTPTokenForm, request.user)
        return auth_views.LoginView.as_view(
            template_name="deploy/totp.html", authentication_form=form_class
        )(request)
    # TODO Make this redirect to the original destination
    return HttpResponseRedirect("/")


def qrcode(request, key=None):
    """
    render a QR code as an SVG image
    """
    try:
        img = render_qrcode(request.user, key)
        response = HttpResponse(content_type="image/svg+xml")
        img.save(response)
    except ImportError:
        response = HttpResponse("", status=503)
    return response


def vpn_client_download(request):
    file_path = "/srv/pancrypticon/openvpn/vpnclient.zip"
    if os.path.exists(file_path):
        with open(file_path, "rb") as fh:
            response = HttpResponse(fh.read(), content_type="application/zip")
            response["Content-Disposition"] = "inline; filename=" + os.path.basename(
                file_path
            )
            return response
    raise Http404


def log_download(request, container_id):
    file_path = "%s/webroot/logs/%s.json.txt" % (settings.BASE_DIR, container_id)
    if os.path.exists(file_path):
        status = get_container_status(container_id)
        log_name = status["name"] if "name" in status else container_id
        log = json2log(file_path)
        response = HttpResponse(log, content_type="text/plain")
        response["Content-Disposition"] = "attachment; filename=%s-%s.log" % (
            log_name,
            container_id,
        )
        return response
    raise Http404


class GenericFormView(FormView):
    def check_totp(self, **kwargs):
        if needs_verification(self.request):
            return HttpResponseRedirect("/accounts/totp/")
        return super(GenericFormView, self).get(self.request, **kwargs)

    def get(self, request, **kwargs):
        return self.check_totp(**kwargs)

    def post(self, request, **kwargs):
        return self.check_totp(**kwargs)


class GenericTemplateView(TemplateView):
    def check_totp(self, **kwargs):
        if needs_verification(self.request):
            return HttpResponseRedirect("/accounts/totp/")
        return super(GenericTemplateView, self).get(self.request, **kwargs)

    def get(self, request, **kwargs):
        return self.check_totp(**kwargs)


class SettingsFormView(GenericFormView):
    template_name = "deploy/settings.html"
    form_class = SettingsForm

    def get_context_data(self, **kwargs):
        context = super(GenericFormView, self).get_context_data(**kwargs)
        context["page_title"] = ugettext("Settings")
        return context

    def get_initial(self):
        """
        load the initial form values from the db
        """
        initial = {
            "timezone": get_config("timezone") or settings.TIME_ZONE,
            "language": get_config("language") or settings.LANGUAGE_CODE,
            "base_domain": get_config("base_domain"),
            "office_domain": get_config("office_domain"),
            "conference_domain": get_config("conference_domain"),
        }
        user = get_user(self.request.user.id)
        if user is not None:
            initial["email_address"] = user.email
        profile = get_profile(self.request.user)
        if profile is not None:
            initial["pgp_key"] = profile.pgp_key
            initial["encrypt_emails"] = profile.encrypt_emails
        return initial

    def post(self, request, **kwargs):
        form = SettingsForm(request.POST)
        if form.is_valid():
            lang_code = form.cleaned_data.get("language")
            set_user(request.user.id, "email", form.cleaned_data.get("email_address"))
            set_profile(request.user, "pgp_key", form.cleaned_data.get("pgp_key"))
            set_profile(
                request.user, "encrypt_emails", form.cleaned_data.get("encrypt_emails")
            )
            set_config("timezone", form.cleaned_data.get("timezone"))
            set_config("language", lang_code)
            set_config("base_domain", form.cleaned_data.get("base_domain"))
            set_config("office_domain", form.cleaned_data.get("office_domain"))
            set_config("conference_domain", form.cleaned_data.get("conference_domain"))
            if hasattr(request, "session"):
                request.session[LANGUAGE_SESSION_KEY] = lang_code
            messages.success(
                request, ugettext("Your settings were updated successfully!")
            )
        else:
            messages.error(
                request,
                ugettext("Could not save settings. Please check the form for errors."),
            )
        return HttpResponseRedirect(reverse("settings"))


class AddSSHKeyFormView(CreateView):
    model = SSHKey
    form_class = AddSSHKeyForm
    template_name = "deploy/add_ssh_key.html"
    success_url = reverse_lazy("list_ssh_keys")

    def get_context_data(self, **kwargs):
        context = super(CreateView, self).get_context_data(**kwargs)
        context["page_title"] = ugettext("SSH Keys")
        return context

    def form_valid(self, form):
        form.instance.added_by = self.request.user
        return super(AddSSHKeyFormView, self).form_valid(form)


class BackupFormView(GenericFormView):
    form_class = BackupForm
    template_name = "deploy/backup.html"

    def get_context_data(self, **kwargs):
        context = super(GenericFormView, self).get_context_data(**kwargs)
        context["page_title"] = ugettext("Backups")
        return context

    def get_initial(self):
        """
        load the initial form value from the db
        """
        initial = {}
        backup_method = None
        if os.path.isfile(settings.BACKUP_PUBLIC_KEY):
            with open(settings.BACKUP_PUBLIC_KEY, "r") as f:
                initial["pubkey"] = f.readlines()[0].rstrip()
        else:
            initial["pubkey"] = ugettext("No key file found.")
        fields = [
            "cifs_target",
            "cifs_username",
            "cifs_password",
            "cifs_domain",
            "method",
            "ssh_target",
        ]
        for field in fields:
            initial["{}".format(field)] = get_config("backup_{}".format(field))
        use_tor = "{}".format(get_config("backup_use_tor"))
        initial["use_tor"] = literal_eval(use_tor)
        return initial

    def post(self, request, **kwargs):
        form = BackupForm(request.POST)
        if form.is_valid():
            # get backup method
            form_value = form.cleaned_data.get("method")
            set_config("backup_method", form_value)
            # choose which fields to process based on backup_method's value
            fields = []
            if form_value == "ssh":
                fields = ["ssh_target"]
            elif form_value == "cifs":
                fields = [
                    "cifs_target",
                    "cifs_username",
                    "cifs_password",
                    "cifs_domain",
                ]
            for field in fields:
                form_value = form.cleaned_data.get(field)
                set_config("backup_{}".format(field), form_value)
            form_value = form.cleaned_data.get("use_tor")
            set_config("backup_use_tor", form_value)
            messages.success(
                request, ugettext("Your settings were saved successfully!")
            )
        return self.check_totp(**kwargs)


class CustomPasswordChangeView(GenericFormView, auth_views.PasswordChangeView):
    def get_context_data(self, **kwargs):
        context = super(GenericFormView, self).get_context_data(**kwargs)
        context["page_title"] = ugettext("Password Change")
        return context

    def post(self, request, **kwargs):
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            set_profile(request.user, "force_password_change", False)
            update_session_auth_hash(request, user)  # Important!
            messages.success(

deploy/templates/deploy/add_ssh_key.html
{% extends 'deploy/wrapper.html' %}
{% load i18n %}
{% load bootstrap4 %}

{% block content %}
<div id="standard-format">
    <p>
        <strong>{% trans 'CAUTION:' %}</strong>
        {% trans "Adding SSH keys will allow 'root' logins on your server." %}
        {% trans 'The root user will have complete and total access to your decrypted data as well as the ability to permanently damage the operating system.' %}
        {% trans 'Use with caution!' %}
        {% trans 'We strongly discourage the use of keys which are not secured with a passphrase.' %}
    </p>
</div>

<form method="post">
    <div id="standard-format">
      {% csrf_token %}
      {% bootstrap_field form.pubkey show_label=False %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">
          {% trans 'Save' %}
        </button>
      {% endbuttons %}
    </form>
    </div>
</form>
{% endblock %}
False

deploy/templates/deploy/deploy.html
{% extends 'deploy/wrapper.html' %}
{% load static %}
{% load i18n %}
{% load bootstrap4 %}
{% block content %}
    <div id="standard-format">
        <p>
            {% trans 'Please enter your encryption passphrase to unlock and launch your Gibberfish cloud.' %}
        </p>
        <div class="hidden" id="install-message">
            {% trans 'Gibberfish is now launching.' %} <strong>{% trans 'Please do not navigate away from this page until it is complete.' %}</strong>
        </div>

        <form action="" class="form">
            {% csrf_token %}
            {% bootstrap_field form.passphrase show_label=False %}
            {% buttons %}
              <button class="hidden" type="submit" class="btn btn-primary">{% trans 'Launch!' %}</button>
            {% endbuttons %}
        </form>
        <p>
          {% if request.GET.force == '1' %}
            {% trans 'Force rebuild:' %} <strong>{% trans 'True' %}</strong>
          {% endif %}
        </p>
        <div class="progress">
            <div class="hidden" id="progressbar"></div>
            <div class="hidden" id="status"></div>
        </div>

        <div class="hidden" id="console">
            <form action="">
                <p>
                    {{ form.output }}
                </p>
            </form>
        </div>

        <div class="hidden" id="success-message">
            {% trans 'Gibberfish was installed successfully!' %} {% blocktrans %}You may now visit <a href='https://{{ nextcloud_domain_name }}' target="_blank">{{ nextcloud_domain_name }}</a> and log in using the following temporary credentials.{% endblocktrans %}
            <br />
            <br />
            {% trans 'Username' %}: <strong>admin</strong>
            <br />
            {% trans 'Passphrase' %}: <strong>{{ admin_passphrase }}</strong>
            <br />
            <br />
            {% trans 'Please change your passphrase once you have logged in.' %}
        </div>
    </div>

    <script type="text/javascript">
        function scrollToBottom() {
            $('#output').scrollTop($('#output')[0].scrollHeight);
        }

        var bar = new ProgressBar.Line('#progressbar', {
          strokeWidth: 2,
          duration: 1400,
          color: '#00adee',
          trailColor: '#eee',
          trailWidth: 1,
          svgStyle: {width: '100%'}
        });
        var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
        var ws = new ReconnectingWebSocket(ws_scheme + '://' + window.location.host + "/ws/");
        ws.debug = true;
        var counter = 0.0;

        ws.onmessage = function(e) {
            data = JSON.parse(e.data)
            if(data.action == 'print'){
                var re = /^(-|ERROR|SUCCESS) (.*)/;
                if(re.test(data.message)){
                    var msg = re.exec(data.message);
                    if(msg[1] == '-' || msg[1] == 'ERROR'){
                        document.getElementById("status").innerHTML = msg[2];
                    }
                    else if (msg[1] == 'SUCCESS') {
                        if("{{ first_run }}".toLowerCase() == "false") {
                            $("#install-message").addClass('hidden');
                            $("#success-message").removeClass('hidden');
                        }
                    }
                }
                $('#output').append(data.message + "\n");
                scrollToBottom();
            }
            else if (data.action == 'start_progress'){
                    counter = 0.0
            }
            else if (data.action == 'increment_progress'){
                if (counter <= 0.90){
                    counter = counter + 0.001
                }
                else if (counter <= 0.99){
                    counter = counter + 0.0001
                }
            }
            else if (data.action == 'stop_progress'){
                counter = 1.0
            }
            bar.animate(counter);  // Number from 0.0 to 1.0
        };

        $('form').submit(
            function(e) {
                passphrase = document.getElementById('passphrase').value;

                $("#submit").attr("disabled", "disabled");
                $("#passphrase").attr("type", "password");
                $("#passphrase").attr("readonly", true);
                $("#passphrase").width('100%')

                ws.send(
                    JSON.stringify(
                        {
                            "action"            : "launch",
                            "admin_email"       : "{{ admin_email }}",
                            "admin_passphrase"  : "{{ admin_passphrase }}",
                            "domain_name"       : "{{ nextcloud_domain_name }}",
                            "office_domain_name": "{{ office_domain_name }}",
                            "conference_domain_name": "{{ conference_domain_name }}",
                            "hidden_domain_name": "{{ hidden_domain_name }}",
                            "language"          : "{{ language }}",
                            "passphrase"        : passphrase,
                            "testing"           : "{{ testing }}",
                            "git_branch"        : "{{ git_branch }}",
                            "force_rebuild"    : "{{ request.GET.force }}",
                        }
                    )
                )

                $("#progressbar").removeClass('hidden');
                $("#status").removeClass('hidden');
                $("#console").removeClass('hidden');
                $("#install-message").removeClass('hidden')
                $("#launcher-text").addClass('hidden')
                $("#passphrase").addClass('hidden')
                document.getElementById("status").innerHTML = "{% trans 'Starting' %}";
                e.preventDefault();
            }
        )

        // Call onopen directly if socket is already open
        if (ws.readyState == WebSocket.OPEN) ws.onopen();
    </script>
{% endblock content %}

deploy/templates/deploy/dns_update.html
{% extends 'deploy/wrapper.html' %}
{% load static %}
{% load i18n %}
{% load bootstrap4 %}

{% block content %}
<div id="standard-format">
    <p>
        {% trans 'If you do not have a static IP address (for instance when using a residential internet connection), you must configure a dynamic DNS update service.' %}
        {% trans 'Contact Gibberfish for the correct settings to enter below.' %}
    </p>
</div>

<form method="post">
    <div id="standard-format">
      {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
          <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
        {% endbuttons %}
    </div>
</form>
{% endblock %}

deploy/templates/deploy/domain_setup.html
{% extends 'deploy/wrapper.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<form method="post">
    <div id="standard-format">
      {% csrf_token %}
      <p>
        {% trans 'Please enter the domain names that have been configured for your Gibberfish cloud.' %}
      </p>
      <p>
        {% trans 'The "base" domain will act as the web address of your server.' %}
        {% trans 'The "office" and "conference" domains will be used for additional services.' %}
        {% trans 'Refer to the Management Portal Guide for more information.' %}
      </p>
        {% bootstrap_form form  %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">
          {% trans 'Save' %}
        </button>
      {% endbuttons %}
    </div>
</form>
{% endblock %}

deploy/templates/deploy/email_change.html
{% extends 'deploy/wrapper.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap4 %}
{% block content %}
<form method="post">
    <div id="standard-format">
      {% csrf_token %}
      <p>
        {% trans 'You must set an email contact to complete your account setup.' %}
      </p>
      {% bootstrap_form form show_label=False%}
      {% buttons %}
        <button type="submit" class="btn btn-primary">
          {% trans 'Save' %}
        </button>
      {% endbuttons %}
    </div>
</form>
{% endblock %}

deploy/templates/deploy/nuke.html
{% extends 'deploy/wrapper.html' %}
{% load static %}
{% load i18n %}
{% load bootstrap4 %}
{% block content %}
<div id="standard-format">
  <p>
    {% trans 'To protect your privacy and safety, we have included a self-destruct option which will irrevocably destroy all of the data on the server.' %}
    {% trans 'Your files will be deleted and then overwritten with random bits several times to prevent their recovery.' %}
  </p>
  <div class="radioactive centered">
    ☢️ ☢️ ☢️
  </div>
  <div class="centered uppercase">
    <strong>
      {% trans 'This procedure is irreversible!' %}
    </strong>
  </div>
</div>

<form method="post">
    <div id="standard-format">
      {% csrf_token %}
      <p class="centered">
        {% trans 'Please manually enter the following confirmation code to proceed:' %}
      </p>
      <p class="centered">
        <strong>{{ form.hidden_confirmation_code.value }}</strong>
      </p>
      {% bootstrap_field form.hidden_confirmation_code %}
      {% bootstrap_field form.confirmation_code show_label=False %}
      {% bootstrap_field form.confirm %}
      {% buttons %}
        <button type="submit" class="btn btn-primary uppercase">{% trans 'self-destruct' %}</button>
      {% endbuttons %}
      </p>
    </div>
</form>
{% endblock %}

deploy/templates/deploy/power_control.html
{% extends 'deploy/wrapper.html' %}
{% load static %}
{% load i18n %}
{% load bootstrap4 %}
{% block content %}
<div id="standard-format">
  <p>
    {% trans "Click the 'Reboot' button below to reboot your server." %}
    {% trans "Please wait several minutes for the reboot to complete." %}
    {% trans "Once the server has restarted, you must re-launch your cloud from the 'Deploy' tab." %}
</p>
</div>

<form method="post">
    <div id="standard-format">
      {% csrf_token %}
      <div class="hidden">
        {% bootstrap_form form %}
      </div>
      {% buttons %}
        <button type="submit" class="btn btn-primary">{% trans 'Reboot' %}</button>
      {% endbuttons %}
    </div>
</form>
{% endblock %}

deploy/templates/deploy/settings.html
{% extends 'deploy/wrapper.html' %}
{% load i18n %}
{% load static %}
{% load bootstrap4 %}
{% block content %}

<div id="standard-format">
  <p>
    <h2>
      {% trans 'Settings' %}
    </h2>
  </p>
    <a href="{% url 'password_change' %}">{% trans 'Click here to change your login passphrase' %}</a>
  </p>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_field form.email_address %}
    {% bootstrap_field form.timezone %}
    {% bootstrap_field form.language %}
    {% bootstrap_field form.show_advanced %}
    <div id="advanced-options" class="hidden" >
      <strong>
        {% trans 'Note:' %} {% trans 'You probably do not want to change these values!' %}
      </strong>
      <p>
        {% bootstrap_field form.base_domain %}
        {% bootstrap_field form.office_domain %}
        {% bootstrap_field form.conference_domain %}
      </p>
    </div>
    <div>
    {% buttons %}
      <button type="submit" class="btn btn-primary">
        {% trans 'Save' %}
      </button>
    {% endbuttons %}
  </form>
</div>

<script type="text/javascript">
  $(function()
    {
      $('[name="show_advanced"]').change(function()
        {
          if ($(this).is(':checked')) {
             $("#advanced-options").removeClass('hidden');
          }
          else {
            $("#advanced-options").addClass('hidden');
          };
        });
      });
</script>

{% endblock %}

deploy/templates/deploy/static_tokens.html
{% extends 'deploy/wrapper.html' %}
{% load i18n %}
{% load static %}
{% block content %}
{% load bootstrap4 %}

<script type="text/javascript" src='{% static "deploy/js/jquery-1.12.1.min.js" %}'></script>

<div id="standard-format">
    <form method="post" action="{% url 'static_tokens' %}">
        {% csrf_token %}
        <div id=static-tokens-confirmation>
            <p>
                {% trans 'Backup tokens are pre-generated codes which will allow you to authenticate without your phone.' %}
                {% trans 'Each code may only be used once.' %}
                {% trans 'When you have used all of your tokens you will be allowed to generate a new set.' %}
            </p>
            <p>
                {% trans "If you would like to add the following tokens to your account, first copy them down somewhere safe and then click 'Confirm'." %}
            </p>
            <div id="token-button">
            </div>
            <div id="token-list">
            {% for t in tokens %}
                <p>{{ t }}</p>
            {% endfor %}
            </div>
            <div id='token-confirm'>
                {% buttons %}
                  <button type="submit" class="btn btn-primary">
                    {% trans 'Confirm' %}
                  </button>
                {% endbuttons %}
                <!-- <input id="submit" type="submit" value="{% trans 'Confirm' %}"> -->
                {{ form.token_list_csv }}
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">
    $("#id_token_list_csv").val("{{ tokens | join:',' }}");
</script>
{% endblock %}

deploy/templates/deploy/totp.html
{% extends 'deploy/wrapper.html' %}
{% load static %}
{% load i18n %}
{% block content %}
{% load bootstrap4 %}

<div id="login-container">
    {% if form.errors %}
        <p>{{ form.otp_token.errors }} {{ form.otp_device.errors }}</p>
    {% endif %}
    <form method="post" action="{% url 'totp' %}">
        {% csrf_token %}
        <div>
          {% trans 'Please enter your 2nd factor code:' %}
        </div>
        <div id="totp-form">
          {% bootstrap_field form.otp_device %}
          {% bootstrap_field form.otp_token %}
            {% buttons %}
              <button type="submit" class="btn btn-primary">
                {% trans 'Verify' %}
              </button>
            {% endbuttons %}

        </div>
    </form>
</div>
{% endblock %}

deploy/templates/deploy/totp_add_device.html
{% extends 'deploy/wrapper.html' %}
{% load static %}
{% load i18n %}
{% load bootstrap4 %}
{% block content %}
<script type="text/javascript" src='{% static "deploy/js/jquery-1.12.1.min.js" %}'></script>

<div id="standard-format">
    <form method="post" action="{% url 'totp_add_device' %}">
        {% csrf_token %}
        <div id="totp-confirmation">
            <p>
                {% trans "Scan this QR code with your OTP app, then generate a 6-digit code and enter it below." %}
            </p>
            <div id="totp-qrcode">
                <img src="/totp/qrcode/{{ device_key }}/">
            </div>
            <div id="totp-confirmation-code">
                {% bootstrap_field form.confirmation %}
                {% buttons %}
                  <button type="submit" class="btn btn-primary">
                    {% trans 'Confirm' %}
                  </button>
                {% endbuttons %}
                <!-- <input id="submit" type="submit" value="{% trans 'Confirm' %}"> -->
                {% bootstrap_field form.key %}
            </div>
            <p>
                {% trans "Once confirmed you will be required to use your mobile device to log in." %}
            </p>
        </div>
    </form>
</div>

<script type="text/javascript">
    $("#id_key").val("{{ device_key }}");
</script>
{% endblock %}